#!/usr/bin/env python3
"""生成 test_index_search 使用的真实 faiss fixture。

用本机 faiss-cpu 训练一个 RVC 形状的 IndexIVFFlat（d=768、METRIC_L2），
write_index 写出 .index（与真实 RVC 训练产物同一序列化布局），
再用 faiss 自身的 search() 计算期望检索结果，供 C++ 单测对照。

内置格式金丝雀：断言写出文件的头部字节与已实证的 faiss 布局一致，
若未来 faiss 改动序列化格式，本脚本会立即失败而不是悄悄产出坏 fixture。

用法：python gen_index_fixture.py   （需要 pip install faiss-cpu numpy）
"""

import struct
from pathlib import Path

import faiss
import numpy as np

D = 768
NLIST = 4
NTOTAL = 64
NQUERIES = 8
INDEX_RATE = 0.75
SEED = 20260928

HERE = Path(__file__).resolve().parent
INDEX_PATH = HERE / "fixtures" / "rvc_ivf_flat_d768.index"
DATA_PATH = HERE / "fixtures" / "rvc_ivf_flat_d768.txt"


def main() -> None:
    rng = np.random.default_rng(SEED)
    # 4 个相互远离的簇：最近质心无歧义、训练后无空表
    centers = rng.normal(0.0, 3.0, (NLIST, D)).astype(np.float32)
    per_cluster = NTOTAL // NLIST
    xb = np.concatenate(
        [centers[i] + rng.normal(0.0, 0.05, (per_cluster, D)) for i in range(NLIST)]
    ).astype(np.float32)

    quantizer = faiss.IndexFlatL2(D)
    index = faiss.IndexIVFFlat(quantizer, D, NLIST, faiss.METRIC_L2)
    index.train(xb)
    index.add(xb)
    assert index.ntotal == NTOTAL

    faiss.write_index(index, str(INDEX_PATH))

    # ── 格式金丝雀：实证布局的关键字节 ──
    raw = INDEX_PATH.read_bytes()
    assert raw[:4] == b"IwFl", f"bad magic: {raw[:4]!r}"
    assert struct.unpack_from("<i", raw, 4)[0] == D
    assert struct.unpack_from("<q", raw, 8)[0] == NTOTAL
    assert struct.unpack_from("<q", raw, 16)[0] == 0x100000, "header marker moved"
    assert struct.unpack_from("<q", raw, 24)[0] == 0x100000, "header marker moved"
    assert raw[32] == 1, "is_trained moved"
    assert struct.unpack_from("<i", raw, 33)[0] == faiss.METRIC_L2
    assert struct.unpack_from("<q", raw, 37)[0] == NLIST, "nlist moved"
    assert raw[53:57] == b"IxF2", "quantizer fourcc moved"
    # 质心紧跟量化器头（offset 98）：首质心必须等于某个训练簇中心
    first_centroid = np.frombuffer(raw, dtype="<f4", count=D, offset=98)
    dists = np.linalg.norm(first_centroid - centers, axis=1)
    assert dists.min() < 0.5, "centroids not where the verified layout says"

    # ── faiss 自身检索结果作为期望值 ──
    queries = np.concatenate(
        [centers[i] + rng.normal(0.0, 0.05, (NQUERIES // NLIST + 1, D)) for i in range(NLIST)]
    ).astype(np.float32)[:NQUERIES]
    _, ix = index.search(queries, 1)
    assert (ix >= 0).all(), "empty list hit: adjust SEED so every list is populated"

    with DATA_PATH.open("w", encoding="utf-8") as f:
        f.write(f"# generated by gen_index_fixture.py (seed={SEED})\n")
        f.write(f"# faiss {faiss.__version__}, IndexIVFFlat d={D} nlist={NLIST} "
                f"ntotal={NTOTAL}, metric=L2, nprobe=1\n")
        f.write(f"d {D}\nnlist {NLIST}\nrate {INDEX_RATE}\n")
        for i in range(NQUERIES):
            nearest = xb[ix[i, 0]]
            blended = (queries[i] * np.float32(1.0 - INDEX_RATE)
                       + nearest * np.float32(INDEX_RATE))
            f.write("query " + " ".join(repr(float(v)) for v in queries[i]) + "\n")
            f.write("expected " + " ".join(repr(float(v)) for v in blended) + "\n")

    size_kb = INDEX_PATH.stat().st_size / 1024
    print(f"wrote {INDEX_PATH} ({size_kb:.1f} KiB) and {DATA_PATH}")


if __name__ == "__main__":
    main()
